# Generated by Django 6.0.5 on 2026-05-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('xp_recompensa', models.IntegerField(default=10)),
                ('concluida', models.BooleanField(default=False)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
